version: 2
jobs:
  android:
    working_directory: ~/dropsoflife
    docker:
      - image: circleci/android:api-28-node8-alpha
    environment:
      _JAVA_OPTIONS: "-Xmx1500m"

    steps:
      - checkout:
          path: ~/dropsoflife

      - attach_workspace:
          at: ~/dropsoflife

      - run: 
          name: Check MD5 on files
          command: |
             md5sum build.gradle
             md5sum app/build.gradle            
             cat app/build.gradle | sed -n -e '/dependencies/,$p' > app.build.gradle.deps

      - restore_cache:
          key: android-jars-v1-{{ checksum "build.gradle" }}-{{ checksum  "app.build.gradle.deps" }}

      - run:
          name: Set Permission
          command: |
            sudo chmod +x ./gradlew 
            sudo echo "storePassword=$storePassword" >> keystore.properties 
            sudo echo "keyPassword=$mykeyPassword" >> keystore.properties 
            sudo echo "keyAlias=$myKeyAlias" >> keystore.properties 
            sudo echo "storeFile=$myStoreFileLocation" >> keystore.properties 

      - run:
          name: Build Android APK
          command: |
            ./gradlew assembleRelease --init-script init.gradle

      - run:
          name: Run Lint Tests
          command: ./gradlew lint test     
            
      - store_artifacts:
          path: app/build/outputs/apk/
          destination: apks/    

      - store_artifacts:
          path: app/build/reports
          destination: reports

      - store_test_results:
          path: app/build/reports/tests/testReleaseUnitTest
 
      - save_cache:
          key: android-jars-v1-{{ checksum "build.gradle" }}-{{ checksum  "app.build.gradle.deps" }}
          paths:
            - ~/.gradle

workflows:
  version: 2
  android-apk:
    jobs:
      - android:
          filters:  
            branches:
              only: master      
